sudo: required
language: cpp
os:
  - linux
  - osx
before_install:
  - git submodule sync --recursive
  - git submodule update --init --recursive
install:
  - bash .travis/install/$TRAVIS_OS_NAME.sh
script:
  - "if which g++-4.8 >/dev/null 2>&1; then export CXX=$(which g++-4.8); export CC=$(which gcc-4.8); else export CXX=$(which g++); export CC=$(which gcc); fi"
  - $CXX --version
  - $CC --version
  - cmake --version
  - cmake . -DCOVERAGE=ON
  - cmake --build .
  - pushd tests
  - ./libvsqtest
  - popd
after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/Applications/Xcode.app/*' --output-file coverage.info
  - lcov --remove coverage.info '/usr/*'                    --output-file coverage.info
  - lcov --remove coverage.info "$(pwd)/ext/*"              --output-file coverage.info
  - lcov --remove coverage.info "$(pwd)/tests/*"            --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash)
